service: serverless-chatbot

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-chatbot

functions:
  bot:
    handler: bot.endpoint
  hello:
    handler: handler.endpoint
    events:
      - http:
          path: echo
          method: post
    environment:
      POST_MESSAGE_URL: 'https://slack.com/api/chat.postMessage?'
      BOT_ACCESS_TOKEN: 'xoxb-1234567890121-AaaAAaa123'
      BOT_ID: 'U4P87QLNL'
      VERIFICATION_TOKEN: 'verification token'
