service: serverless-chatbot

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-chatbot
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:DetectFaces
      Resource: '*'
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.uploadBucket}/*
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.transformBucket}/*
custom:
  uploadBucket: ${self:service}-${self:provider.stage}-uploads-your-initials-here
  transformBucket: ${self:service}-${self:provider.stage}-transformed-your-initials-here
functions:
  hello:
    handler: handler.endpoint
    events:
      - http:
          path: echo
          method: post
    environment:
      POST_MESSAGE_URL: 'https://slack.com/api/chat.postMessage?'
      BOT_ACCESS_TOKEN: 'xoxb-1234567890121-AaaAAaa123'
      VERIFICATION_TOKEN: 'verification token'
      UPLOAD_BUCKET: ${self:custom.uploadBucket}
      SLACK_HOSTNAME: 'files.slack.com'
      TEMP_FOLDER: '/tmp/'
  faceswap:
    handler: faceswap.execute
    environment:
      TEMP_FOLDER: '/tmp/'
      OUTPUT_PREFIX: 'output-'
      UPLOAD_BUCKET: ${self:custom.uploadBucket}
      TRANSFORM_BUCKET: ${self:custom.transformBucket}
    events:
      - s3:
          bucket: ${self:custom.uploadBucket}
          event: s3:ObjectCreated:*
  slackupdate:
    handler: slackupdate.execute
    events:
      - s3:
          bucket: ${self:custom.transformBucket}
          event: s3:ObjectCreated:*